### ISSUE TITLE
Wheel for v0.4.5 does not match source code

### ISSUE THREAD

**Issue by sjdines** [graphql-python/graphql-relay-py#23]
When looking at https://pypi.org/project/graphql-relay/0.4.5/#files there appears to be a mistaken upload of the wheel package to v0.4.5.

The wheel appears to be newer code than that marked for v.0.4.5 in the source code with the newly updated requirements

**Comment by hvdklauw** [comment]
Yeah:
```
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    graphql-relay==0.4.5 from https://files.pythonhosted.org/packages/86/12/8de5918c2dfcb53958a3767d4e2df9918b603d9a468810c44156fe79faeb/graphql_relay-0.4.5-py3-none-any.whl#sha256=80750a57f8d9b7dc548195c7b5b9a2ae7f5d006f11963181ed768e3709952513 (from -r requirements.txt (line 394)):
        Expected sha256 2716b7245d97091af21abf096fabafac576905096d21ba7118fba722596f65db
             Got        80750a57f8d9b7dc548195c7b5b9a2ae7f5d006f11963181ed768e3709952513
```

**Comment by hvdklauw** [comment]
The source seems to be the same, and indeed the requirements seem changed, but it's only the graphql-core < 2 restriction seems added.

**Comment by hvdklauw** [comment]
ok, took some digging.

But the <2 restriction is actually a problem !

Before I had the following versions: 
`graphene = "2.1.6"`
which has the following requirement:
`graphql-core = ">=2.1,<3"`

And the source version of `graphql-relay = "0.4.5"` which has 
`graphql-core = ">=0.5.0"`

Which is all fine and works fine.
But with the <2 restriction for graphql-core on the wheel of graphql-relay this is no longer a workable combination.

**Comment by hvdklauw** [comment]
Ah and graphene has:
`graphql-relay>=0.4.5,<1",`

So can't install a newer version of graphql-relay either.

Maybe we need a 0.4.6 release to fix things?

**Comment by phihag** [comment]
Better yet, restore 0.4.5 to the old state.
Then, if you want to perform any changes in dependencies or otherwise, release 0.4.6.

**Comment by benhowes** [comment]
With pipenv, I've been able to work around this for graphene-django (until it's resolved properly) by doing:
```
pipenv uninstall graphene
pipenv install -e git+https://github.com/graphql-python/graphql-relay-py.git@48856fb3cf9e6c122535076a82d862bac3c21779#egg=graphql-relay
pipenv install graphene-django 
```

Where that middle line installs the commit from https://github.com/graphql-python/graphql-relay-py/commit/48856fb3cf9e6c122535076a82d862bac3c21779

I would imagine that you can change the last line to just install graphene if required, but I've not tested. 

This was enough to get us up and running for now

**Comment by lionasp** [comment]
Any updates for this issue?

**Comment by prokher** [comment]
Seems to be a crucial one. Our CI has stopped working in spite of all the package versions are frozen!

**Comment by MrSaints** [comment]
We're using Poetry, and currently getting around the problem using (similar to @benhowes):

```
graphql-relay = { git = "https://github.com/graphql-python/graphql-relay-py.git", rev = "48856fb3cf9e6c122535076a82d862bac3c21779" }
```

Inside `pyproject.toml`.

**Comment by hvdklauw** [comment]
Yeah does not work for me.

My build chain is poetry for development and for ci/production we use:
```poetry export -f requirements.txt
pip install -r requirements.txt --prefer-binary
```
This has a way faster installation time then using poetry, but it also disallows source versions because they have no hash.

There is no fix unless they pull the wheel from pypi or release a new version that has workable restrictions on the versions.

**Comment by krishnaku** [comment]
All our builds with frozen dependencies started failing this morning. Seems like reverting the wheel is a necessary first step and perhaps then releasing a 0.4.6? This is a pretty crucial issue as it is blocking pushing any new changes to CI.

**Comment by JKillian** [comment]
Using `pipenv`, updating to the new hash seemed to fix the issue for me:

```diff
        "graphql-relay": {
            "hashes": [
-               "sha256:2716b7245d97091af21abf096fabafac576905096d21ba7118fba722596f65db"
+               "sha256:80750a57f8d9b7dc548195c7b5b9a2ae7f5d006f11963181ed768e3709952513"
            ],
            "version": "==0.4.5"
        },
```

**Comment by Cito** [comment]
Just had a look. I think what happened is this:

* Version 0.4.5 had been available as a tar.gz only on PyPI so far, with restriction graphql-core>=0.5
* The restriction graphql-core<2 has been added to relay-py (which is correct, since version 0.4.5 only works properly with graphql-core<2)
* The new wheel for 0.4.5 with that descriction has been added to PyPI, probably accidentally by Travis when adding a tag.
* The problem arises because Graphene requires graphql-core>=2, but graphql-relay<1 which is a contradiction. It probably only worked so far because the tar.gz did not have the restriction.

The proper fix in my view is to release a new Graphene patch version that proprely requires graphql-relay>=2,<3.

**Comment by krishnaku** [comment]
I concur that the proper fix is to update a new Graphene patch version. 

That said, we have graphene-relay 0.4.5 working with graphene-core 2.0 without issues (at least ones that affect our use cases). Even assuming there is a patch released shortly,  updating graphene versions requires a more through test cycle and in the meantime all our CI builds are broken with the above change and no code can be pushed anymore.

Is it possible to revert back to just serving the tar.gz for version 0.4.5 instead of the wheel with the new restriction? I understand that there are incompatibilities between graphene-relay 0.4.5 and graphene-core 2.0, but at least we can address them or upgrade as we find they are material.

Thanks for looking into this.

**Comment by Cito** [comment]
We will look if it is possible to delete the wheel (needs someone with admin rights) or whether we simply publish a 0.4.6 without that restriction.

**Comment by krishnaku** [comment]
Thank you!

**Comment by rectalogic** [comment]
The hash of 0.4.5 will be wrong unless the 0.4.5 wheel is deleted.
```
graphql-relay==0.4.5 \
    --hash=sha256:2716b7245d97091af21abf096fabafac576905096d21ba7118fba722596f65db \
```

**Comment by armenzg** [comment]
In my Docker file I work around it by installing the source package directly before trying to use the requirements file:

```
RUN pip install https://files.pythonhosted.org/packages/5e/b0/b91fadc180544fc9e3c156d7049561fd5f1e2211d26fd29033548fd50934/graphql-relay-0.4.5.tar.gz
RUN pip install --no-cache-dir --disable-pip-version-check --require-hashes -r requirements/common.txt
```

**Comment by mvanlonden** [comment]
The wheel has been deleted. Sorry for any inconvenience this may have caused.

**Comment by krishnaku** [comment]
Thanks for the quick resolution! Much appreciated.

**Comment by Cito** [comment]
The problematic wheel has now been deleted.
